# Generated by Django 3.2.8 on 2021-10-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='totalPages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
