# Generated by Django 3.2.8 on 2021-10-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_reader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteBook',
        ),
        migrations.DeleteModel(
            name='UpdateBook',
        ),
    ]
