# Generated by Django 3.2.8 on 2021-10-14 12:41

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211009_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default.jpg', upload_to=api.utils.upload_to, verbose_name='Image'),
        ),
    ]
